"""refactor of secondary

Revision ID: 6d9a202ab922
Revises: 4358728b89e1
Create Date: 2024-02-06 20:57:31.611147

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6d9a202ab922"
down_revision: Union[str, None] = "4358728b89e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_conversation", sa.Column("user_id", sa.Uuid(), nullable=False))
    op.add_column(
        "user_conversation", sa.Column("conversation_id", sa.Uuid(), nullable=False)
    )
    op.drop_constraint("unique_pair_keys", "user_conversation", type_="unique")
    op.create_unique_constraint(
        "unique_pair_keys", "user_conversation", ["user_id", "conversation_id"]
    )
    op.drop_constraint(
        "user_conversation_conversation_fk_fkey",
        "user_conversation",
        type_="foreignkey",
    )
    op.drop_constraint(
        "user_conversation_user_fk_fkey", "user_conversation", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "user_conversation", "conversation", ["conversation_id"], ["id"]
    )
    op.create_foreign_key(None, "user_conversation", "user", ["user_id"], ["id"])
    op.drop_column("user_conversation", "user_fk")
    op.drop_column("user_conversation", "conversation_fk")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_conversation",
        sa.Column("conversation_fk", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_conversation",
        sa.Column("user_fk", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "user_conversation", type_="foreignkey")
    op.drop_constraint(None, "user_conversation", type_="foreignkey")
    op.create_foreign_key(
        "user_conversation_user_fk_fkey",
        "user_conversation",
        "user",
        ["user_fk"],
        ["id"],
    )
    op.create_foreign_key(
        "user_conversation_conversation_fk_fkey",
        "user_conversation",
        "conversation",
        ["conversation_fk"],
        ["id"],
    )
    op.drop_constraint("unique_pair_keys", "user_conversation", type_="unique")
    op.create_unique_constraint(
        "unique_pair_keys", "user_conversation", ["user_fk", "conversation_fk"]
    )
    op.drop_column("user_conversation", "conversation_id")
    op.drop_column("user_conversation", "user_id")
    # ### end Alembic commands ###
