"""AAAs

Revision ID: 3550b0c13b95
Revises: b11b5c276e18
Create Date: 2024-02-06 00:46:34.312486

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3550b0c13b95"
down_revision: Union[str, None] = "b11b5c276e18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("conversation_user_admin_fk_key", "conversation", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "conversation_user_admin_fk_key", "conversation", ["user_admin_fk"]
    )
    # ### end Alembic commands ###
