"""refactor of secondary

Revision ID: b88a5ea9dcf5
Revises: f042cfa8ed39
Create Date: 2024-02-06 19:45:01.103433

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b88a5ea9dcf5"
down_revision: Union[str, None] = "f042cfa8ed39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_conversation_conversation_fk_fkey",
        "user_conversation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "user_conversation", "conversation", ["conversation_fk"], ["id"]
    )
    op.drop_column("user_conversation", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_conversation",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    )
    op.drop_constraint(None, "user_conversation", type_="foreignkey")
    op.create_foreign_key(
        "user_conversation_conversation_fk_fkey",
        "user_conversation",
        "conversation",
        ["conversation_fk"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
