"""User unique=True migration3

Revision ID: 24b86cfa14d1
Revises: e5b9d9651c33
Create Date: 2024-02-04 04:14:01.028780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "24b86cfa14d1"
down_revision: Union[str, None] = "e5b9d9651c33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("user", "is_online")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("is_online", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
