"""Added active and updated fields to User model

Revision ID: 7a5fbba3c24b
Revises: b6be8db1a4d8
Create Date: 2024-02-29 16:43:31.979208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a5fbba3c24b"
down_revision: Union[str, None] = "b6be8db1a4d8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message", "status", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("message", "status", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
