"""Added

Revision ID: 38955182b01b
Revises: f79aaef58ae5
Create Date: 2024-02-18 00:11:13.918493

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38955182b01b"
down_revision: Union[str, None] = "f79aaef58ae5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "conversation_user_admin_fk_fkey", "conversation", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "conversation", "user", ["user_admin_fk"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint("message_conversation_fk_fkey", "message", type_="foreignkey")
    op.create_foreign_key(
        None, "message", "conversation", ["conversation_fk"], ["id"], ondelete="Cascade"
    )
    op.drop_constraint(
        "user_conversation_user_id_fkey", "user_conversation", type_="foreignkey"
    )
    op.drop_constraint(
        "user_conversation_conversation_id_fkey",
        "user_conversation",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "user_conversation", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "user_conversation",
        "conversation",
        ["conversation_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_conversation", type_="foreignkey")
    op.drop_constraint(None, "user_conversation", type_="foreignkey")
    op.create_foreign_key(
        "user_conversation_conversation_id_fkey",
        "user_conversation",
        "conversation",
        ["conversation_id"],
        ["id"],
    )
    op.create_foreign_key(
        "user_conversation_user_id_fkey",
        "user_conversation",
        "user",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_conversation_fk_fkey",
        "message",
        "conversation",
        ["conversation_fk"],
        ["id"],
    )
    op.drop_constraint(None, "conversation", type_="foreignkey")
    op.create_foreign_key(
        "conversation_user_admin_fk_fkey",
        "conversation",
        "user",
        ["user_admin_fk"],
        ["id"],
    )
    # ### end Alembic commands ###
