"""refactor of secondary

Revision ID: 4a4ee2571cd2
Revises: 6d9a202ab922
Create Date: 2024-02-07 22:55:59.051113

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a4ee2571cd2"
down_revision: Union[str, None] = "6d9a202ab922"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
