"""Added active and updated fields to User model

Revision ID: bedd3a4e04ae
Revises: 7a5fbba3c24b
Create Date: 2024-02-29 19:39:41.706000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bedd3a4e04ae"
down_revision: Union[str, None] = "7a5fbba3c24b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("message_conversation_fk_key", "message", type_="unique")
    op.drop_constraint("message_user_fk_fkey", "message", type_="foreignkey")
    op.create_foreign_key(
        None, "message", "user", ["user_fk"], ["id"], ondelete="Cascade"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "message", type_="foreignkey")
    op.create_foreign_key(
        "message_user_fk_fkey", "message", "user", ["user_fk"], ["id"]
    )
    op.create_unique_constraint(
        "message_conversation_fk_key", "message", ["conversation_fk"]
    )
    # ### end Alembic commands ###
