
services:
  test_db:
    image: postgres:16.2-alpine3.19
    restart: always
    container_name: test_db
    env_file:
      - .env-test-db
    ports:
      - '5433:5432'
    networks:
      - my_network
    

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/root/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    env_file:
      - .env-test-db
    networks:
      - my_network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - fast_app
      - fast_app_2
      - fast_app_3
    restart: always
    networks:
      - my_network

  fast_app:
    image: fastproject-fast_app:latest
    env_file:
      - .env-docker-comm
    container_name: app
    expose:
      - "8000"
    depends_on:
      - redis
      - test_db  
    command: ["gunicorn", "main:app", "--workers", "12", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]

    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    networks:
      - my_network

  fast_app_2:
    image: fastproject-fast_app:latest
    env_file:
      - .env-docker-comm
    container_name: app2
    expose:
      - "8001"
    depends_on:
      - redis
      - test_db  
    command: ["gunicorn", "main:app", "--workers", "12", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8001"]

    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    networks:
      - my_network

  fast_app_3:
    image: fastproject-fast_app:latest
    env_file:
      - .env-docker-comm
    container_name: app3
    expose:
      - "8002"
    depends_on:
      - redis
      - test_db  
    command: ["gunicorn", "main:app", "--workers", "12", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8002"]

    volumes:
      - ./src:/app/src
      - ./alembic:/app/alembic
    networks:
      - my_network



networks:
  my_network:
    driver: bridge
  