services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env_minio
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
