services:

  db:
    container_name: db
    image: postgres:16.4-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5433:5432"
    volumes:
      - ./mydata:/var/lib/postgresql/data 
    env_file:
      - .env_postgres

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    env_file:
      - .env_kafka


  minio:
    